<?php
// Plugin definition
$plugin = array(
  'title' => t('Industry Hub'),
  'icon' => 'industryhub.png',
  'category' => t('Tieto'),
  'theme' => 'industryhub',
  'css' => 'industryhub.css',
  'regions' => array(
    'header' => t('Header'),
    'column1' => t('First Column'),
    'column2' => t('Second Column'),
    'middle' => t('Middle'),
    'secondcolumn1' => t('Bottom First Column'),
    'secondcolumn2' => t('Bottom Second Column'),
    'footer' => t('Footer'),
  ),
);
