<?php
// Plugin definition
$plugin = array(
  'title' => t('Whelan Stacked 2'),
  'icon' => 'whelan-stacked2.png',
  'category' => t('Tieto'),
  'theme' => 'whelan-stacked2',
  'css' => 'whelan-stacked2.css',
  'regions' => array(
    'column1' => t('First Column'),
    'column2' => t('Second Column'),
    'contentmain' => t('Content main'),
    'contentbottom' => t('Content Middle'),
    'contentshare' => t('Content Bottom'),
  ),
);
